baseURL = 'https://blog.chipzciptadi.com/'
languageCode = 'en-us'
title = 'Ciptadi Blog'

theme = "anubis"

[taxonomies]
tags = "tags"

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = "0"

[params]
author = "Ciptadi"
email = "chipz.ciptadi@gmail.com"
dateFormat = "January 2, 2006"
style = "auto"